### ISSUE TITLE
Problems encountered using Add-ons m3u-browser.lua

### ISSUE THREAD

**Issue by liJie-wk** [CogentRedTester/mpv-file-browser#101]
When I set addons to yes, my "MENU script binding file_browser/browse files" in input.cnf becomes invalid and cannot display the file_ Browser interface. If addons=no, it can be displayed normally. Here is my file path
![屏幕截图_20231213_173028](https://github.com/CogentRedTester/mpv-file-browser/assets/57932868/a751f366-b3ec-47a9-9dae-dc6f63138b7e)

**Comment by CogentRedTester** [comment]
Most probably the script is crashing. Check the console output for any error messages, and if they don't explain what the problem is upload a log file generated with `--log-file=log.txt --msg-level=file_browser='debug'`.

**Comment by liJie-wk** [comment]
> Most probably the script is crashing. Check the console output for any error messages, and if they don't explain what the problem is upload a log file generated with `--log-file=log.txt --msg-level=file_browser='debug'`.
I understand the reason. It was the error message 'wget not available in the system PATH' reported by read-file.lua, and I installed wget myself to solve the problem

**Comment by liJie-wk** [comment]
> Most probably the script is crashing. Check the console output for any error messages, and if they don't explain what the problem is upload a log file generated with `--log-file=log.txt --msg-level=file_browser='debug'`.

I understand the reason. It was the error message 'wget not available in the system PATH' reported by read-file.lua, and I installed wget myself to solve the problem
