### ISSUE TITLE
I hope to expand the range of support for play-autoload

### ISSUE THREAD

**Issue by liJie-wk** [CogentRedTester/mpv-file-browser#105]
When I play videos without going through the operation interface of the MPV file browser, I can only load playlist entries before and after the selected file using autoload.lua. However, the file sorting rules of autoload.lua are inconsistent with mpv file browser，this makes me very uncomfortable

**Comment by CogentRedTester** [comment]
How are they different?

**Comment by liJie-wk** [comment]
> 它们有什么不同？
It's already done because the default file format added by autoload.lua is not as many as mpv file browser, which leads to inconsistent playlists between both parties

**Comment by liJie-wk** [comment]
> How are they different?

It's already done because the default file format added by autoload.lua is not as many as mpv file browser, which leads to inconsistent playlists between both parties
