### ISSUE TITLE
Can alt+o be disabled by default, otherwise an error will be thrown if accidentally triggered.

### ISSUE THREAD

**Issue by zhouxinghong** [CogentRedTester/mpv-file-browser#107]
Can alt+o be disabled by default, otherwise an error will be thrown if accidentally triggered.
`[file_browser] Lua error: ...Player/mpv/portable_config/scripts/file-browser/main.lua:58: attempt to call field 'get_user_input' (a nil value)`

Once the above error occurs, the entire file browsing function will no longer be available.

Windows 10

Because I couldn't find [mpv-user-input](https://github.com/CogentRedTester/mpv-file-browser?tab=readme-ov-file#mpv-user-input) after searching for a long time. Maybe this function is not commonly used.

**Comment by CogentRedTester** [comment]
Oh it's supposed to be, this is a bug.

**Comment by CogentRedTester** [comment]
Should be fixed.

**Comment by zhouxinghong** [comment]
Because I couldn't find [mpv-user-input](https://github.com/CogentRedTester/mpv-file-browser?tab=readme-ov-file#mpv-user-input) after searching for a long time
