### ISSUE TITLE
Sorting requires a leading zero

### ISSUE THREAD

**Issue by twophyro** [CogentRedTester/mpv-file-browser#11]
Currently the sorting of filenames seems to require a leading zero.

The result ends up looking like this:

- Episode 1 - Episode name
- Episode 10 - Episode name
- Episode 11 - Episode name
- Episode 12 - Episode name
- Episode 2 - Episode name

Is it possible to make it so a leading zero is no longer required.
Or is this a limitation of MPV?

**Comment by twophyro** [comment]
`function alphanumsort(o)
  local function padnum(d) local r = string.match(d, "0*(.+)")
    return ("%03d%s"):format(#r, r) end
  table.sort(o, function(a,b)
    return tostring(a):gsub("%d+",padnum) < tostring(b):gsub("%d+",padnum) end)
  return o
end`

Looks like this fixes it

**Comment by CogentRedTester** [comment]
Oh, looks promising. I'll test it soon and make the change if everything works properly.
