### ISSUE TITLE
Support for using mpv's internal `mp.input` function

### ISSUE THREAD

**Issue by dyphire** [CogentRedTester/mpv-file-browser#111]
I modified the find.lua addons to use it on newer mpv.
```lua
--[[
    An addon for mpv-file-browser for searching the current directory
    Available at: https://github.com/CogentRedTester/mpv-file-browser/tree/master/addons

    Requires mpv-user-input: https://github.com/CogentRedTester/mpv-user-input

    Keybinds:
        Ctrl+f  open search box
        Ctrl+F  open advanced search box (supports Lua patterns)
        n       cycle to next valid item
]]--

local msg = require "mp.msg"
local fb = require "file-browser"
local success, input = pcall(require, 'mp.input')
if not success then
    -- Requires: https://github.com/CogentRedTester/mpv-user-input
    user_input_module, input = pcall(require, "user-input-module")
end

local find = {
    version = "1.3.0"
}
local latest_coroutine = nil
local global_fb_state = getmetatable(fb.get_state()).__original

local function compare(name, query)
    if name:find(query) then return true end
    if name:lower():find(query) then return true end
    if name:upper():find(query) then return true end

    return false
end

local function main(key, state, co)
    if not state.list then return false end

    local text
    if key.name == "find/find" then text = "Find: enter search string"
    else text = "Find: enter advanced search string" end

    local query, error = nil, nil
    if user_input_module then
        query, error = coroutine.yield(
            input.get_user_input( fb.coroutine.callback(), { text = text, id = "find", replace = true } )
        )
    elseif input then
        query, error = coroutine.yield(
            input.get({
                prompt = text .. "\n>",
                id = "find",
                submit = fb.coroutine.callback(),
            })
        )
    end

    if not query then
        return msg.debug(error)
    elseif query and not user_input_module then
        input.terminate()
    end

    -- allow the directory to be changed before this point
    local list = fb.get_list()
    local parse_id = global_fb_state.co

    if key.name == "find/find" then
        query = fb.pattern_escape(query)
    end

    local results = {}

    for index, item in ipairs(list) do
        if compare(item.label or item.name, query) then
            table.insert(results, index)
        end
    end

    if (#results < 1) then
        msg.warn("No matching items for '"..query.."'")
        return
    end

    --keep cycling through the search results if any are found
    --putting this into a separate coroutine removes any passthrough ambiguity
    --the final return statement should return to `step_find` not any other function
    fb.coroutine.run(function()
        latest_coroutine = coroutine.running()
        while (true) do
            for _, index in ipairs(results) do
                fb.set_selected_index(index)
                coroutine.yield(true)

                if parse_id ~= global_fb_state.co then
                    latest_coroutine = nil
                    return false
                end
            end
        end
    end)
end

local function step_find()
    if not latest_coroutine then return false end
    return fb.coroutine.resume_err(latest_coroutine)
end

find.keybinds = {
    {"Ctrl+f", "find", main, {}},
    {"Ctrl+F", "find_advanced", main, {}},
    {"n", "next", step_find, {}},
}

return find

```

**Comment by CogentRedTester** [comment]
I don't want to migrate file-browser or any of the addons to use mp.input officially yet as the api is only available in mpv v0.38 while this script still supports versions going back to v0.33. My distro's repos don't even have v0.38, so I'm not even running it yet.

That said, if I do look into bumping the minimum version in a couple of years I'll refer back to this.

**Comment by dyphire** [comment]
> I don't want to migrate file-browser or any of the addons to use mp.input officially yet as the api is only available in mpv v0.38 while this script still supports versions going back to v0.33. My distro's repos don't even have v0.38, so I'm not even running it yet.
> 
> That said, if I do look into bumping the minimum version in the next couple of years I'll refer back to this.

It's not necessary to improve the minimum version support, it's perfectly fine to retain user-input-module compatibility as I did with the find.lua script modification.

**Comment by CogentRedTester** [comment]
That's true, but I'd rather not maintain two ways of doing the same thing unless there's a good reason. I would definitely like to switch to using mp.input as it will be the standard for MPV scripts going forward, but as far as I'm aware it would not actually provide any tangible benefits over mpv-user-input. So since I'm in no rush, I'd rather just wait a year or so and do a full switch and version bump once v0.38 is more mature.

That said if you wanted to make one or more PRs you're welcome to, I'd likely accept them.

**Comment by dyphire** [comment]
> but as far as I'm aware it would not actually provide any tangible benefits over mpv-user-input

The mp.input inside mpv already supports historical search records, and third-party osc scripts have better support, such as uosc. The mpv-user-input does not work well with uosc controls in idle state.

> That said if you wanted to make one or more PRs you're welcome to, I'd likely accept them.

I will open a PR to implement it.
