### ISSUE TITLE
Video duration

### ISSUE THREAD

**Issue by tiberiuiurco** [CogentRedTester/mpv-file-browser#115]
Is there any way to activate/ implement the duration for each video file in the menu?

**Comment by tiberiuiurco** [comment]
Thank you for the quick reply. I've been using this addon a lot, on a daily basis.
For example, sometimes when I am going somewhere and riding the train, I download the course I am studying beforehand.
The courses are usually structured in lectures/ episodes. So, when opening the menu browser, it would be extremely useful if you could see how long each video is, before opening it. That way, you don't have to manually check the duration. Sometimes you only have 30 minutes free time, so you might want to watch something that is less than that.
I attached a picture. I am not at home right now so I cant create a high quality drawing, but there you go.
For each video file (ignore the ones that are not videos - e.g. subtitles), the total duration o
f a video in HH:SS could be shown after/ before the file name. If the video is 13 seconds -> make it 1 minute (edge case).

Is this functionality already supported? 

Thank you.

![bunny](https://github.com/user-attachments/assets/c2e30c2d-2f13-409e-b683-08ee68a8b28a)

**Comment by CogentRedTester** [comment]
Hey, sorry for the late reply. It can be done with addons, though it would slow down how long it takes to open a directory (at least the first time), and it would require an additional commandline application to grab the duration information.

Here is an addon that does it with `ffprobe`:

```lua
-- An addon for mpv-file-browser (https://github.com/CogentRedTester/mpv-file-browser)
-- which appends the duration of a media file to the end of it's name in the browser.
-- Requires `ffprobe` (part of ffmpeg) to be in the system path.

local mp = require 'mp'
local msg = require 'mp.msg'
local utils = require 'mp.utils'

local fb = require 'file-browser'

local addon = {
    version = '1.4',
    priority = 20,
}

local cache = setmetatable({}, {__mode = 'k'})

local function get_duration(path)
    if cache[path] then return cache[path] end
    cache[path] = '~'

    local args = {
        'ffprobe', '-v', 'error', '-show_entries', 'format=duration',
        '-of', 'default=noprint_wrappers=1:nokey=1', '-pretty',
        '-i', path
    }

    msg.debug('running command', utils.to_string(args))

    local cmd = mp.command_native_async({
        name = 'subprocess',
        playback_only = false,
        capture_stdout = true,
        capture_stderr = true,
        args = args,
    }, fb.coroutine.callback(60, path))

    local success, _, res = coroutine.yield()
    if not success then
        mp.abort_async_command(cmd)
        cache[path] = nil
        return msg.error('ffprobe into', path, 'timed out.')
    end

    if res.status ~= 0 then
        cache[path] = nil
        msg.warn('failed to get duration for', path)
        return msg.error(res.stderr)
    end

    cache[path] = string.match(res.stdout, '%d+:%d+:%d+')
    return cache[path]
end

local function queue_coroutine(fn)
    mp.add_timeout(0, function() fb.coroutine.run(fn) end)
end

function addon:can_parse(directory, parse_state)
    return directory ~= '' and parse_state.source == 'browser'
end

function addon:parse(directory, ...)
    local list, opts = self:defer(directory, ...)
    if not list then return list, opts end

    local counter = 0
    local cb = fb.coroutine.callback(10, directory)

    for _,item in ipairs(list) do
        if item.type == 'file' then
            counter = counter + 1
            queue_coroutine(function()
                local original = (item.label or item.name)
                item.label = original..'\t[~]'

                local duration = get_duration(fb.get_full_path(item, opts.directory or directory))
                if duration and duration ~= '0:00:00' then
                    item.label = original..'\t['..duration..']'
                else
                    item.label = original
                end

                -- only resume the coroutine once all the async operations are done
                counter = counter - 1
                if counter == 0 then cb() end
            end)
        end
    end

    if counter == 0 then mp.add_timeout(0, cb) end

    -- wait until all the async operations are complete
    local success = coroutine.yield()
    if not success then msg.warn('duration requests timed out') end

    return list, opts
end

return addon
```

I've set a 10 second timeout to prevent the delays from being too long. If a file was not processed in that time then the duration will be shown as `~`.  The duration detection continues in the background, so you can refresh the browser (Ctrl+r) if some of the durations did not show up.

**Comment by tiberiuiurco** [comment]
Thank you for the answer.
Unfortunately, it does not work for me. 
After adding the addon, the video files completely dissapear from the menu.
Is there something that I m missing? Like a dependency or something?

**Comment by tiberiuiurco** [comment]
I also have 777 permissions to files.
Other files like subtitles get recognized, apart from videos.

**Comment by CogentRedTester** [comment]
Upload a log file.

**Comment by tiberiuiurco** [comment]
[output.txt](https://github.com/user-attachments/files/18216546/output.txt)
Here it is

**Comment by CogentRedTester** [comment]
Are you waiting 10 seconds for the duration to be calculated?

**Comment by tiberiuiurco** [comment]
Yep. A lot more..

**Comment by tiberiuiurco** [comment]
I tried again on a folder with only two videos. Here is another log.
[output.txt](https://github.com/user-attachments/files/18216601/output.txt)

**Comment by CogentRedTester** [comment]
Can you show some screenshots of what the browser looks like?

**Comment by tiberiuiurco** [comment]
![image](https://github.com/user-attachments/assets/2571db7e-22ae-4817-9374-6634d1eca136)
No videos showing

**Comment by CogentRedTester** [comment]
Ok, I believe I have found the issue. I've updated the above addon with a fix, can you try again?

**Comment by tiberiuiurco** [comment]
Now it works!! 
Thank you so much!!
