### ISSUE TITLE
does not work in macos environment

### ISSUE THREAD

**Issue by tnira** [CogentRedTester/mpv-file-browser#18]
Thanks for the useful script.

In an environment that utilizes windows10, the script works well.
But, it did not work well in macOS11 environment.

I run the command `mpv --msg-level=all=trace` in macOS environment and post a message related to this script.
Could you give me some advice on how to make the script work?

```
[file_browser] Loading lua script /Users/tnira/.mpv/scripts/file-browser.lua...
[scroll_list] loading mp.defaults
[file_browser] loading mp.defaults
[scroll_list] loading file /Users/tnira/.mpv/scripts/scroll-list.lua
[file_browser] loading file /Users/tnira/.mpv/scripts/file-browser.lua
[file_browser] 
[file_browser] stack traceback:
[file_browser] 	[C]: ?
[file_browser] 	[C]: ?
[file_browser] Lua error: [string "/Users/tnira/.mpv/scripts/file-browser.lua"]:282: '=' expected near 'continue'
[file_browser] Exiting...
```

**Comment by CogentRedTester** [comment]
That is strange. Can you post the whole log file produced by `--log-file=file.log`

**Comment by tnira** [comment]
Could you check this file, please?

[file.log](https://github.com/CogentRedTester/mpv-file-browser/files/5656437/file.log)

**Comment by CogentRedTester** [comment]
I believe the issue here is that your copy of mpv is using an older version of lua which the script currently doesn't support.

**Comment by CogentRedTester** [comment]
Try this: https://github.com/CogentRedTester/mpv-file-browser/blob/lua5.1/file-browser.lua

**Comment by tnira** [comment]
Thanks for trying to deal with it.
I replaced [file-browser.lua](https://github.com/CogentRedTester/mpv-file-browser/commit/e4994f9f7d55a19d31d07d8665657aff49f3eef1)  and tried again.
[file2.log](https://github.com/CogentRedTester/mpv-file-browser/files/5656856/file2.log)
It still did not work well.
I'm going to try various mpv build options to check them out.

**Comment by CogentRedTester** [comment]
That's a strange error, it's different from the last one, but it shouldn't be possible based on my understanding of the code. Anyway, I've pushed a fix for what I think is the issue in that branch. Try downloading the file again and seeing if it works.

**Comment by tnira** [comment]
Worked on this [commit](https://github.com/CogentRedTester/mpv-file-browser/commit/15608d6fbbb21aa5f7ece6a1f399b17f6f512abd).

Thank you for your work.

On a different note, is it correct to say that the garbled folder icons are a separate issue from this script?
![Screen Shot 2020-12-08 at 14 51 43](https://user-images.githubusercontent.com/3020006/101445601-2169e400-3965-11eb-9c17-59f383981e0f.jpg)

**Comment by CogentRedTester** [comment]
Way ahead of you, check out the latest commit.

**Comment by CogentRedTester** [comment]
It seems that the default fonts used by mpv on macOS don't support those characters. You can either download better fonts, or use the new options to customise what characters show up.

**Comment by tnira** [comment]
Works fine!
Thank you very much.

**Comment by CogentRedTester** [comment]
I may tidy up some of these changes and then push them into the master branch, having the script work by default on macOS is worth more than the new lua features.

**Comment by CogentRedTester** [comment]
I have added an example to `file_browser.conf` to explain how to set a custom font specifically for an icon, just in-case you were unaware.
