### ISSUE TITLE
No longer works on Windows 10

### ISSUE THREAD

**Issue by twophyro** [CogentRedTester/mpv-file-browser#24]
Latest update no longer works on Windows 10.

Files:

```
script-opt > file_browser.conf (Only edited root=C:/,E:/,G:/,R:/)
script-opt > file-browser-keybinds.json
scripts > file-browser.lua
scripts > scroll-list.lua
scripts > user-input.lua
scripts > user-input-module.lua
```

All of these are the latest version

Pressing TAB `(TAB script-binding browse-files in input.conf)` does nothing.
When running in Powershell mpv.com TAB does nothing and nothing shows in Powershell

**Comment by twophyro** [comment]
Using `file-browser.lua` from `no-scroll-list` tree works.

**Comment by CogentRedTester** [comment]
Can you post a log

**Comment by twophyro** [comment]
> [file_browser]
> [file_browser] stack traceback:
> [file_browser]  [string "C:/Users/iay/Desktop/mpv/scripts/file-browser..."]:1178: in main chunk
> [file_browser]  [C]: at 0x007b2ff0
> [file_browser]  [C]: at 0x007b1a00
> [file_browser] Lua error: cannot open C:\Users\iay\AppData\Roaming/mpv/script-modules/user-input-module.lua: Invalid argument

**Comment by CogentRedTester** [comment]
Ah right, woops
________________________________

**Comment by CogentRedTester** [comment]
user-input-module needs to go into  `~~/script-modules/`.

The here is that it wasn't supposed to be compulsory.

**Comment by twophyro** [comment]
Would it be possible to move it in to `file-browser.conf` where the user gets to define where their MPV installation is, or is that too clumsy?

**Comment by CogentRedTester** [comment]
I can allow people to modify the path if you like, I moved the directory to `~~/script-modules/` because I didn't want mpv to also be loading modules that it wasn't going to use..

**Comment by CogentRedTester** [comment]
Also the crashing should now be fixed after the latest commit

**Comment by twophyro** [comment]
It works now 👍

**Comment by CogentRedTester** [comment]
You can now modify the module directory.

**Comment by twophyro** [comment]
I don't know how you want to continue with this but looking at the code it's able to load `file-browser-keybinds.json` fine even though it looks similar in `file-browser.lua`

**Comment by CogentRedTester** [comment]
The keybinds json file is only loaded when `custom_keybinds` is enabled in `file_browser.conf`, so it's fine. In fact, if custom_keybinds is enabled and the file is not in the correct place then the code is specifically designed to throw an error letting you know that the keybinds failed to load.

**Comment by twophyro** [comment]
Thanks for the help 👍
