### ISSUE TITLE
don't want to show all type of file formats

### ISSUE THREAD

**Issue by Max-Enrik** [CogentRedTester/mpv-file-browser#25]
I'd like to exclude .str file formats. Is there a chance to do it?

**Comment by CogentRedTester** [comment]
The `filter_files` script-opt controls this, and it should be set to `yes` by default. `.str` files are not one of the default enabled file extensions so they should be hidden.

**Comment by Max-Enrik** [comment]
Unfortunately, it still shows `.str` files. Are below lines could be like these?
_( I only placed these files in proper locations - `file-browser.lua` and `file_browser.conf` )_

_These in file_browser.conf file._
```
filter_files=yes
extension_blacklist=.str
```

**Comment by CogentRedTester** [comment]
you don't include the `.` when listing the file extensions in the blacklist

**Comment by Max-Enrik** [comment]
I still see `.str` files.

`extension_blacklist=str`

**Comment by CogentRedTester** [comment]
You'll need to provide a bit more info then, upload a full log produced by the --log-file option

**Comment by CogentRedTester** [comment]
Also upload some screenshots of what's being shown

**Comment by Max-Enrik** [comment]
Where is that log file?

**Comment by CogentRedTester** [comment]
you set the --log-file option in mpv to the filepath of the resulting log file, for example `--log-file=~~desktop/log.txt`

**Comment by Max-Enrik** [comment]
Nice, I see log file now. There are a lot of personal folder/files and some PC infos. Could you tell me which part of the log reports that I have to provide you, because its huge reports?

**Comment by CogentRedTester** [comment]
Upload the whole thing, I'll know what to look for. Also upload a screenshot of file-browser showing the .str file.

**Comment by CogentRedTester** [comment]
If you must then just do a ctrl+h and remove the personal folders with ~~~

**Comment by Max-Enrik** [comment]
OK, when I will make a time I will jump to other PC to make a `log.txt` file and will share whole reports here. Because now it will take a lot of time to remove and check carefully before I post it here, good to be make it in other PC share whole thing without removing anything.

**Comment by Max-Enrik** [comment]
Here you go.
[log.txt](https://github.com/CogentRedTester/mpv-file-browser/files/6339251/log.txt)

**Comment by CogentRedTester** [comment]
Did you actually open file browser and move to the directory containing the files when you made that log? Because I don't see it reflected there

**Comment by Max-Enrik** [comment]
OK, I made a screenshots for you.
[https://i.snipboard.io/sm0S3E.jpg](url)

**Comment by CogentRedTester** [comment]
That isn't an 'str' file, it's an 'srt' file. Srt is a valid subtitle extension format, as is txt.

**Comment by CogentRedTester** [comment]
So you need to blacklist 'srt' not 'str'

**Comment by Max-Enrik** [comment]
Dayuum! It was killer of my time. : /

Thank you for mentioned it and for your time.

**Comment by rsingh2083** [comment]
> I'd like to exclude .str file formats. Is there a chance to do it?

Can anyone please tell me how to run this application, Im getting this error :-
```

└──╼ $lua file-browser.lua 
lua: file-browser.lua:11: module 'mp' not found:
	no field package.preload['mp']
	no file '/usr/local/share/lua/5.2/mp.lua'
	no file '/usr/local/share/lua/5.2/mp/init.lua'
	no file '/usr/local/lib/lua/5.2/mp.lua'
	no file '/usr/local/lib/lua/5.2/mp/init.lua'
	no file '/usr/share/lua/5.2/mp.lua'
	no file '/usr/share/lua/5.2/mp/init.lua'
	no file './mp.lua'
	no file '/usr/local/lib/lua/5.2/mp.so'
	no file '/usr/lib/x86_64-linux-gnu/lua/5.2/mp.so'
	no file '/usr/lib/lua/5.2/mp.so'
	no file '/usr/local/lib/lua/5.2/loadall.so'
	no file './mp.so'
stack traceback:
	[C]: in function 'require'
	file-browser.lua:11: in main chunk
	[C]: in ?
```
