### ISSUE TITLE
Cannot find main.* for any supported scripting backend

### ISSUE THREAD

**Issue by bparker06** [CogentRedTester/mpv-file-browser#26]
I think this script needs updating for the newer version of mpv ?

**Comment by CogentRedTester** [comment]
`file-browser.lua` cannot be inside a folder in the `~~/scripts` directory, if must be in the top level.

**Comment by bparker06** [comment]
Where is this documented?

**Comment by CogentRedTester** [comment]
https://mpv.io/manual/master/#script-location

**Comment by bparker06** [comment]
Ok, I didn't want to pollute the top-level folder so I just renamed the script main.lua and kept it in its own directory and that seems to work.
