### ISSUE TITLE
How to use ftp-browser and apache-browser addons?

### ISSUE THREAD

**Issue by izumi46** [CogentRedTester/mpv-file-browser#31]
My operating system is Windows.I have put the files on the appropriate file directory and installed curl.but I don't know how to browser,windows should be used to add different drive letters,how to add ftp or http?

**Comment by izumi46** [comment]
Thanks, Now I know how to use it.

**Comment by CogentRedTester** [comment]
Also if you have mpv-user-input installed (see [here](https://github.com/CogentRedTester/mpv-file-browser#mpv-user-input)) then you can open an input field and load the server directly without needing to modify the root.
