### ISSUE TITLE
When appending files to playlist, it autoloads files in the same folder?

### ISSUE THREAD

**Issue by MintMain21** [CogentRedTester/mpv-file-browser#33]
According to the documentation on this Github repo, "Autoload" (the process of appending files from the same directory to the playlist/queue) should be disabled by default. This is true when selecting files to override current playback, but when holding "SHIFT" to append files it will queue up everything else in the same folder. Only workaround is to select the single file with S and then SHIFT+ENTER to append to playlist. I'm reporting this because it does not seem to be intentional on the developer's part and may qualify as a bug (or a conflict).

Using the most up-to-date release of MPV from the MPV-Tests Repo (Linux Mint 20.2) I am willing to purge this PPA and resort to distro default if it will fix the issue.

**Comment by CogentRedTester** [comment]
Should be fixed now

**Comment by MintMain21** [comment]
No problem. And thanks for fixing it.
