### ISSUE TITLE
file-browser.lua 0f4d581 doesn't start - caused by favourites addon

### ISSUE THREAD

**Issue by ereinstein** [CogentRedTester/mpv-file-browser#35]
I saw that you updated `file-browser.lua` 28 days ago. Because of that, I replaced the `file-browser.lua` in my config with the newest one but that makes the script not respond at all. `MENU` doesn't open the file browser any more. Prior, I was on [this specific version](https://github.com/CogentRedTester/mpv-file-browser/blob/80df446add5d6f130c76837399a68fe3a3e04c83/file-browser.lua) of the script. 

The last section called "mpv-user-input Compatability" is missing in the newer versions. Could this be responsible for this problem? I guess it isn't broken on your side, otherwise you wouldn't have shipped four more versions since then. 

I am on mpv version 0.34.0-100-g0e76372e86 which is the newest git master as of writing this.

**Comment by CogentRedTester** [comment]
Sounds like the script is crashing. Please pray the crash report from the terminal and upload an mpv log.

**Comment by ereinstein** [comment]
```
file_browser: 
file_browser: stack traceback:
file_browser:   [C]: in function 'insert'
file_browser:   [string "/home/bruh/.config/mpv/scripts/file-browser.l..."]:415: in function 'insert_root_item'
file_browser:   ...ig/mpv/script-modules/file-browser-addons/favourites.lua:71: in function 'setup'
file_browser:   [string "/home/bruh/.config/mpv/scripts/file-browser.l..."]:1446: in main chunk
file_browser:   [C]: in ?
file_browser:   [C]: in ?
file_browser: Lua error: [string "/home/bruh/.config/mpv/scripts/file-browser.l..."]:415: bad argument #2 to 'insert' (number expected, got table)
```

**Comment by CogentRedTester** [comment]
Oh, did you update the addons you're using as well? A number of API calls were updated in the new version, so you may need to update the addons you're using as well.

**Comment by CogentRedTester** [comment]
I'll need to start creating version numbers so it's clear of the addon API changes

**Comment by ereinstein** [comment]
I updated `favourites.lua` as well, which is the only addon I am using but I still have the same issue. 
```
file_browser: 
file_browser: stack traceback:
file_browser:   [C]: in function 'insert'
file_browser:   [string "/home/bruh/.config/mpv/scripts/file-browser.l..."]:415: in function 'insert_root_item'
file_browser:   ...ig/mpv/script-modules/file-browser-addons/favourites.lua:43: in function 'setup'
file_browser:   [string "/home/bruh/.config/mpv/scripts/file-browser.l..."]:1446: in main chunk
file_browser:   [C]: in ?
file_browser:   [C]: in ?
file_browser: Lua error: [string "/home/bruh/.config/mpv/scripts/file-browser.l..."]:415: bad argument #2 to 'insert' (number expected, got table)
```
Only the problematic line in `favourites.lua` seems to have changed.

**Comment by ereinstein** [comment]
Removing my `file_browser.conf` allows the script to start again. Let me find out what changed in the configuration file.

**Comment by CogentRedTester** [comment]
Yes, I've already figured out the issue. Will fix in the next couple if days.

**Comment by CogentRedTester** [comment]
That last commit should have fixed it, can you confirm? I'm away from my computer so can't get myself.

**Comment by ereinstein** [comment]
It works now!
