### ISSUE TITLE
Need to customize keys.

### ISSUE THREAD

**Issue by Max-Enrik** [CogentRedTester/mpv-file-browser#37]
What have I done before I ask here?
Need to customize keys.
- file-browser-keybinds.json > script-opts folder
- custom_keybinds=yes > file_browser.conf
- s script-binding scroll_down > input.conf
- s script-binding scroll-down > input.conf

Unfortunately, nothing changed.

**Comment by CogentRedTester** [comment]
You need to use the `file-browser-keybinds.json` file to modify the key binds. See the [documentation](https://github.com/CogentRedTester/mpv-file-browser/blob/master/custom-keybinds.md#modifying-default-keybinds).

**Comment by Max-Enrik** [comment]
I'd like to use two different keys like `WHEEL_UP` and `w` just for `scroll_up`. Is it possible? If yes, how?
