### ISSUE TITLE
Need to change - font / font size

### ISSUE THREAD

**Issue by Max-Enrik** [CogentRedTester/mpv-file-browser#38]
I need to be able to change the font and the font size. How can I do it?

What have I done so far?

- checked > readme.md
- checked > file_browser.conf
- checked > file-browser.lua

**Comment by CogentRedTester** [comment]
Ok, in the latest commits I have now added options to set names, sizes, and colours of all fonts.

**Comment by Max-Enrik** [comment]
Thank you so much more. Those are fantastic!

**Comment by Max-Enrik** [comment]
Misspelling > file_browser.conf
#92 font_name_cusor= (missing 'r' in cursor)

**Comment by CogentRedTester** [comment]
Thank you for catching that, it's been fixed.
