### ISSUE TITLE
Force file-browser to be left aligned

### ISSUE THREAD

**Issue by Max-Enrik** [CogentRedTester/mpv-file-browser#39]
The osd alignment is a right. But I need the file browsers that would be Left.

**Comment by CogentRedTester** [comment]
I don't quite understand, can you be more specific? Are you saying you have set the osd-alignment to be right, but you want file-browser to be aligned left?

**Comment by Max-Enrik** [comment]
Yes, you are correctly understood.

**Comment by CogentRedTester** [comment]
Should be fixed in the latest commit

**Comment by Max-Enrik** [comment]
Cool! Thank you!
