### ISSUE TITLE
Folder - Size / Files / Empty

### ISSUE THREAD

**Issue by Max-Enrik** [CogentRedTester/mpv-file-browser#40]
Is it possible to see a folder's size, how many files are in it, and if it's empty?

**Comment by CogentRedTester** [comment]
It's possible, but it would potentially be a very time intensive operation. Detecting the folder size especially, imagine you're in the root, detecting a folder's size would require parsing through 100s of thousands of directories.

For these reason's I will not be adding this feature to the browser, but it could be done with an addon. I don't have the time to write it myself, but you or someone else are free to do so.

I'm going to close this issue now, but if I ever do write an addon that does this, which is unlikely, then I will update this thread.
