### ISSUE TITLE
How do I use the addons?

### ISSUE THREAD

**Issue by Kayizoku** [CogentRedTester/mpv-file-browser#42]
I am unable to get favorites addon or any other to work. I have done everything as described, added favourites.lua to ~/script-modules/file-browser-addons, sat addon=yes, and custom_keybinds=yes in file-browser conf too. But nothing happens. Whenever I press F as noted to be the hotkey for toggling Favorite virtual directory.

**Comment by CogentRedTester** [comment]
Are you using `~~/script-modules/file-browser-addons'? `~/` usually refers to a different folder.

**Comment by CogentRedTester** [comment]
You should know it's shrugged because the Favourites directory appears in the root. F toggles whether or not the current selected item should be added to the favourites.

**Comment by Kayizoku** [comment]
That's right, I dropped an image with my current folder setup. That's right, isn't it? Isn't there a OSD message that should appear when I toggle a current folder into favs?

![image](https://user-images.githubusercontent.com/28716224/148083408-d1e1e538-df80-46fd-8c8b-d09ac16c2c7b.png)

**Comment by CogentRedTester** [comment]
No there isn't any feedback. You just need to look in the favourites directory.

**Comment by CogentRedTester** [comment]
Can you confirm that that isn't happening?

**Comment by Kayizoku** [comment]
> Can you confirm that that isn't happening?

Oh, sorry about that. I have still been unable to get it to work. If I press on the shortcut nothing happens, while the file browser is open or otherwise. I don't see any favorites added to the root section. It's simply empty. My virtual directories I added in script-opts for conf are not showing up either. I should be seeing my drive there's but it's completely empty.

**Comment by CogentRedTester** [comment]
Can you post screenshots of your root directory and an mpv log as output by the `--log-file` option.

**Comment by CogentRedTester** [comment]
You have incorrectly named your `script-opts` folder, you have it named script*s*-opts.

**Comment by CogentRedTester** [comment]
`file-browser-keybinds.json` should also be in the `script-opts` folder

**Comment by Kayizoku** [comment]
Oh, I made one of those mistakes. Guess it happens to the best of us. Thank you, that was it. Now everything is functioning well :)

**Comment by Kayizoku** [comment]
I just got some ideas I would like to request to be implemented if it's no issue. It would be really cool if the ALT+o browser directory could search all files in the favorited folder. What's more what if you add the ability to search directly for the folders that are listed under favorites. So instead of going back and entering into the specific favorite folder. You can just write in the actual name by ALT+O and there you go.

**Comment by CogentRedTester** [comment]
You can already use `Favourites/item` in the `Alt+o` dialogue box to open something in the favourites directory. There is also a find addon for searching the current directory, and you can easily set a keybind that automatically opens favourites. I don't really want to modify the dialogue box for an addon which isn't strictly supported, but you're welcome to create your own addon that searches favourites only if those features aren't enough. Or you could set a keybind to both open favourites and open the find dialogue box.

**Comment by amir28** [comment]
Hello @CogentRedTester
This was my first mpv script which I installed and I was confused on where the .conf file shoud be placed. after reading this issue I figure out that it should be in `script-opts` and worked. please add it in README.md for newbies like me. thanks

**Comment by CogentRedTester** [comment]
> Hello @CogentRedTester This was my first mpv script which I installed and I was confused on where the .conf file shoud be placed. after reading this issue I figure out that it should be in `script-opts` and it worked. please add it in README.md for newbies like me. thanks

Done, but next time please make a post in the discussions tab instead of posting on an unrelated issue.
