### ISSUE TITLE
Trying to make custom keybind behave like arrow keys

### ISSUE THREAD

**Issue by PoisonFrog** [CogentRedTester/mpv-file-browser#44]
I set up some vim-like keybindings so I can move between files and folders. I did it like this:

```
[
        {
        "key": "k",
        "command": ["script-binding", "file_browser/dynamic/scroll_up"]
    },
    {
        "key": "j",
        "command": ["script-binding", "file_browser/dynamic/scroll_down"]
    },
    {
        "key": "h",
        "command": ["script-binding", "file_browser/dynamic/up_dir"]
    },
    {
        "key": "l",
        "command": ["script-binding", "file_browser/dynamic/down_dir"]
    }
]
```

But when I keep the key pressed it doesn't scroll like it does with arrow keys. I have to release the key and press it again to move down or up a list. Is it possible to make it behave like the default keys?

**Comment by CogentRedTester** [comment]
It is possible, you need to use the `flags` field.

It would look something like:

```json
"flags": { "repeatable": true} 
```

**Comment by PoisonFrog** [comment]
> It is possible, you need to use the `flags` field.
> 
> It would look something like:
> 
> ```json
> "flags": { "repeatable": true} 
> ```

Worked perfectly. Thank you very much!
