### ISSUE TITLE
Feature Request: Searching?

### ISSUE THREAD

**Issue by MintMain21** [CogentRedTester/mpv-file-browser#45]
Similar to your Youtube Search plugin, It might be cool to search files using this plugin as an alternative keybinding. It should, naturally, only search in folders already accessible by the File Manager, which is to say files already specified by the user.

**Comment by CogentRedTester** [comment]
Is the [find](https://github.com/CogentRedTester/mpv-file-browser/blob/master/addons/find.lua) addon not good enough? You can combine it with Favourites to only search through a set list of files.

**Comment by MintMain21** [comment]
Sorry, I didn't realize that was there. Thanks.
