### ISSUE TITLE
play_or_down_dir  command

### ISSUE THREAD

**Issue by stax76** [CogentRedTester/mpv-file-browser#53]
An idea for an additional command, in case it's easy to do, and you like the idea:

command name: play_or_down_dir

In case the selection is a file, play it,
in case the selection is a directory, enter the directory.

I think I would favor this behavior.

**Comment by CogentRedTester** [comment]
This can already be very easily done with a [custom keybind](https://github.com/CogentRedTester/mpv-file-browser/blob/master/custom-keybinds.md):

```json
    {
        "key": "ENTER",
        "command": ["script-binding", "file_browser/dynamic/down_dir"],
        "filter": "dir",
    }
```

**Comment by stax76** [comment]
Works great, thanks!
