### ISSUE TITLE
Is there a way to open favorites with just a keybind?

### ISSUE THREAD

**Issue by Cananbolt** [CogentRedTester/mpv-file-browser#54]
I really like this script so far. However, I would like to know if there is a way to open favorites right away and not go all the way back to the root folder. Is it possible to make a keybind in input.conf that would bring up the favorites folder?

**Comment by CogentRedTester** [comment]
Yes, use the [browse-directory script message](https://github.com/CogentRedTester/mpv-file-browser#browse-directory).
