### ISSUE TITLE
OSD overlap

### ISSUE THREAD

**Issue by stax76** [CogentRedTester/mpv-file-browser#56]
For my use case, it would be helpful if file-browser would clear the OSD before showing, in order to avoid overlap.

**Comment by CogentRedTester** [comment]
Are you talking about disabling the whole OSD while the browser is open or just removing any temporary OSD messages that happen to be showing at the time?

**Comment by CogentRedTester** [comment]
If you just want to clear any lingering messages you could just change your keybind to do it in `input.conf`:

`MENU script-binding browse-files ; show-text ""`

If you want to disable the whole OSD you could just do an auto-profile like:
```properties
[hide-osd]
profile-cond=shared_script_properties["file_browser-open"] == "yes"
profile-restore=copy
osd-level=0
```

**Comment by stax76** [comment]
Thanks
