### ISSUE TITLE
Add it mplug script directory

### ISSUE THREAD

**Issue by z8512** [CogentRedTester/mpv-file-browser#60]
Mplug is like a package manager but for mpv scripts.
Please add your script there (if already not there) and also installation instructions in manifest - https://github.com/Nudin/mpv-script-directory/blob/master/HOWTO_ADD_INSTALL_INSTRUCTIONS.md

**Comment by CogentRedTester** [comment]
I don't think you need my help to do any of this, you're free to add entries for my scripts yourself.
