### ISSUE TITLE
Detection of deleted files and folders

### ISSUE THREAD

**Issue by stax76** [CogentRedTester/mpv-file-browser#61]
Deleting files might be a common use case. I download everything with a Chrome extension called [External Application Launcher](https://chrome.google.com/webstore/detail/external-application-laun/bifmfjgpgndemajpeeoiopbeilbaifdo) and yt-dlp.

I have my own script for file deletion and found two other.

https://github.com/jonniek/mpv-scripts/blob/master/trashfileonend.lua

https://github.com/zenyd/mpv-scripts/blob/master/delete_file.lua

https://github.com/stax76/mpv-scripts/blob/main/delete-current-file.lua

If you like the idea, and it's easy to do, maybe you could detect deletions by checking all files if the folder hasn't too many files (people often have fast SSD drives). Or react to a script message from my script. What do you think?

**Comment by CogentRedTester** [comment]
Detecting changes in the filesystem is definitely out of scope for this script.

You can of course manually refresh the directory with the `Ctrl+r` keybind.
You can also refresh the page with the `script-binding file_browser/dynamic/reload` command. But that may only work while file-browser is open.

**Comment by CogentRedTester** [comment]
If that isn't enough I could maybe add another script message that refreshes the directory even when the browser is closed.

**Comment by CogentRedTester** [comment]
In the meantime you can just add this as an addon:

```lua
local mp = require "mp"
local fb = require "file-browser"

mp.register_script_message("refresh-directory", function(directory)
    local browser_directory = fb.get_directory()
    directory = fb.fix_path(directory, true)

    -- if the directory is already open then rescan, if it is a higher level directory then clear the cache
    if directory == browser_directory then
        fb.rescan()
    elseif browser_directory:find(directory) == 1 then
        fb.clear_cache()
    end
end)
```

Send a script message with the absolute path of the directory you want to refresh and it will handle it.

**Comment by stax76** [comment]
Thank you for the support. What also seem to work is an input command:

Ctrl+F script-message osc-idlescreen no no_osd; script-binding file_browser/open-browser; show-text ' '; script-binding file_browser/dynamic/reload

**Comment by CogentRedTester** [comment]
If that works too then great.
