### ISSUE TITLE
OSC disappears after selecting files

### ISSUE THREAD

**Issue by charbelsako** [CogentRedTester/mpv-file-browser#67]
I read here that you are hiding the [osc](https://github.com/CogentRedTester/mpv-file-browser/issues/55) _intentionally_ I think.

Running on Windows 10

Steps to reproduce: 

- Set up the script 
- No custom `keybinds`
- Run a file
- Multiselect some files
- Press `ENTER`
- `OSC` is gone.

**Comment by CogentRedTester** [comment]
Yes, the idea is that if you opening a file to play it then you wouldn't want to keep browsing.

**Comment by CogentRedTester** [comment]
Or are you talking about the actual On Screen Controller being completely disabled after multiselecting things? Because that is not what happens on my end.

**Comment by charbelsako** [comment]
After I select them and press enter the first video starts and the seek bar plus the subtitle selector and all that disappear.

**Comment by CogentRedTester** [comment]
Can you upload a log file generated with `--log-file`.

**Comment by charbelsako** [comment]
formatted my computer unfortunately. No longer have the same config

**Comment by CogentRedTester** [comment]
So does that mean you can't reproduce this bug any more? Because if not then we can close this issue.
