### ISSUE TITLE
Couldn't access drives other than C:/

### ISSUE THREAD

**Issue by eXil3d** [CogentRedTester/mpv-file-browser#68]
My current root in ocnfig looks like this : root=~/,C:/,D:/,E:/,F:/,G:/
After pressing ctrl+o, it shows ~/. when i click right arrow, it takes me to C:/Users/User . then i click the left arrow until I reach to C:/ and 1 more lfet arrow click and I'm in ~/ again.
How do I access the other drives?
I haven't messed with other configs.
![Screenshot_11](https://user-images.githubusercontent.com/63705579/192560741-e509b975-cfd4-48bd-bcc3-9432162bcb16.png)
![Screenshot_10](https://user-images.githubusercontent.com/63705579/192560771-85415b73-0ee5-4940-addc-81ae9b8eb1d6.png)

**Comment by CogentRedTester** [comment]
You must be using the wrong config file, it's just showing the default root value.

**Comment by eXil3d** [comment]
here is my config file (changed the extension to txt as gh doesn't support .conf files)
[file_browser.txt](https://github.com/CogentRedTester/mpv-file-browser/files/9658442/file_browser.txt)

**Comment by CogentRedTester** [comment]
That checks out, the issue then is where you've placed the config file. Make sure that it's in the `~~/script-opts` directory

**Comment by eXil3d** [comment]
thanks. created script-opts folder and pasted the conf file and now it's working.
