### ISSUE TITLE
Font drawing indent issue on Linux

### ISSUE THREAD

**Issue by stax76** [CogentRedTester/mpv-file-browser#69]
I copied my Windows conf to use on Linux and got a minor issue, folders and files are indented differently:

![Screenshot from 2022-09-30 09-35-25](https://user-images.githubusercontent.com/11410540/193217899-e78cc043-2146-4add-a081-a9930fcb20ed.png)

**Comment by CogentRedTester** [comment]
Most probably your Linux machine's default font does not support the Unicode folder symbol I'm using. You can change the icon to one you do have with the `folder_icon` script-opt, or change the font to one that supports the default icon with the `font_name_folder` script-opt. You can also add/remove hard spaces (`\h`) from the `folder_icon`, `cursor_icon`, and `indent_icon` (the default indent for unselected items) script-opts to better customise the indentation for your system.

The specific icon being used by folders by default is `🖿` [U+1F5BF](https://www.fileformat.info/info/unicode/char/1f5bf/index.htm), which is honestly not supported by many fonts. I would prefer to change it to one that is better supported, but I am yet to find a symbol that I think looks as good.

**Comment by stax76** [comment]
I remember now that the font does not even support a simple smiley, which is surprising, I use Ubuntu 22.04. Maybe I can find a better font. Thanks for the quick support.

**Comment by CogentRedTester** [comment]
It's possible your machine has the right fonts but mpv isn't trying to use them. That link I sent you has a list of supported fonts that you could try. I have had success with `Symbola` in the past.

**Comment by stax76** [comment]
I found a related issue on the mpv tracker:

https://github.com/mpv-player/mpv/issues/9073

So far I tried `osd-font = 'Ubuntu Mono'`, that didn't fix it:

`[osd/libass] fontselect: failed to find any fallback with glyph 0x1F642 for font: (Ubuntu Mono, 400, 0)`

I will have to try something else.

**Comment by stax76** [comment]
`Symbola` works, but I don't like the Serif style.

**Comment by CogentRedTester** [comment]
Remember you don't need to apply the font to the whole OSD, you can just use the `font_name_folder` script-opt to only apply the font to the icon.

**Comment by stax76** [comment]
With that, it looks fine, thanks!
