### ISSUE TITLE
Folders and files should be displayed alphabetically

### ISSUE THREAD

**Issue by shag00** [CogentRedTester/mpv-file-browser#7]
Installed the browser which works which is great but when I open a folder the files are listed all over the place. In this instance my files are episodes named as follows S01E01 for season 1, episode 1 through to , say, S10E22, being season 10, episode 22. Listing them in in alphabetical order would be very helpful.

**Comment by CogentRedTester** [comment]
It should be listed in whatever order mpv's `readdir()` command returns.

**Comment by CogentRedTester** [comment]
If you play the whole folder in mpv what order are the files added to the playlist?

**Comment by shag00** [comment]
I am not aware of this readdir command so I played 1 folder and the episodes play sequentially as you would expect, with episode 1 playing first followed sequentially by the rest. I tested the first 8 episodes only.

**Comment by CogentRedTester** [comment]
You'll need to provide more information: your OS, the version of mpv, a full list of all the files in the folder with their exact names. Also upload a log of you navigating to the directory.

**Comment by CogentRedTester** [comment]
Just to clarify, this is working on my end, so I need some more information on why it's not working on yours.

**Comment by shag00** [comment]
Thank you for your fast reply. To set the scene I  have a media server with thousands of videos on it, do you want a full listing of all videos and audio tracks on the server or do you want just an example folder? If you just want an example folder I will choose a small one which is more manageable.

The folder I have been using is called Season 2, the files names are near identical starting at S02E01 R, So2E02 R, sequentially up to S02E23 R, in +1 increments. I am happy to provide a copy of the log but it is unclear to me which log you want. What I am doing at the moment while I am setting mpv up is to go to my file manager and right click the file and select open with mpv. Once mpv launches I hit the Menu key to bring up the menu (list of files).

My OS is Kubuntu 20.04, mpv is 0.32.0

**Comment by CogentRedTester** [comment]
I can tell you right now that the readdir command sorts lowercase letters below capital letters.

**Comment by CogentRedTester** [comment]
It'd be good you sent me screenshots the directory that's open so I can see the whole list.

**Comment by shag00** [comment]
I have been scrupulous with my casing though I can always make an error so I suspect this is not the issue.

![mpv file list](https://user-images.githubusercontent.com/37562304/92422801-38a40480-f1b1-11ea-9801-e33c81e4dbd1.png)

**Comment by CogentRedTester** [comment]
Yes, it definitely looks fine. Create a log file for mpv by sending `--log-file=log.txt` as a command line option, navigate to this directory, then close mpv and upload the file. I may do some testing later today on an Ubuntu system to see if the way `readdir` detects files is different.

**Comment by CogentRedTester** [comment]
I just pushed a commit with more useful debug info, please update the script and send me a log using that.

**Comment by shag00** [comment]
[log.txt](https://github.com/CogentRedTester/mpv-file-browser/files/5185592/log.txt)

**Comment by shag00** [comment]
To clarify what I did.
1. navigate to directory
2. start mpv from command line with log arguement
3. start file browser with keyboard button
4. escape file browser
5. close mpv

**Comment by CogentRedTester** [comment]
Yes, It's looking like the Ubuntu version of the `readdir` command might not sort things in alphabetical order. I'll test this myself when I get the chance later today, If I can confirm that this is the case I'll probably add sorting. In the meantime, maybe you could check if this happens when navigating to a non-smb directory?

**Comment by shag00** [comment]
The actual testing I am doing is on the server, the screenshot I posted was faster to get from my personal PC using samba as it was only the list of files you wanted.

________________________________

**Comment by CogentRedTester** [comment]
What OS is the server then? And does this still happen when navigating to that folder on your personal pc?

**Comment by shag00** [comment]
I have confused you unfortunately, so to clear it up please be advised that everything I have submitted, with the exception of the screenshot of the contents of the folder Season 02, has originated from the server. Let this not distract you.

**Comment by CogentRedTester** [comment]
Ok good, I'll get back to you when I've checked how Ubuntu returns files on my computer.

**Comment by CogentRedTester** [comment]
Ok, I've confirmed that Linux returns files in a random order; I'll implement a sorting algorithm shortly.

**Comment by CogentRedTester** [comment]
Thanks on bringing this to my attention, I tested this on windows, and just assumed that Linux returned files in a sane order as well. It's rare that windows is the more reliable OS.
