### ISSUE TITLE
Detect Directory Automatically ?

### ISSUE THREAD

**Issue by PhoenixCODE2322** [CogentRedTester/mpv-file-browser#71]
currently this has to be done `root=~/,C:/,D:/,E:/` , is there a way to automatically detect directory, like if a plug in a usb drive or external HDD later , will i have to add that drive letter file_browser.conf ?

**Comment by CogentRedTester** [comment]
Normally you would need to do it manually or use the [mpv-user-input dialogue box](https://github.com/CogentRedTester/mpv-file-browser#mpv-user-input) to open the drive directly. But here is an [addon](https://github.com/CogentRedTester/mpv-file-browser#add-ons) I quickly wrote that will add drives to the root automatically:

```lua
--[[
    Automatically populates the root with windows drives on startup.
    Ctrl+r will add new drives mounted since startup.

    Drives will only be added if they are not already present in the root.
]]

local mp = require 'mp'
local msg = require 'mp.msg'
local fb = require 'file-browser'

local function get_drives()
    local result = mp.command_native({
        name = 'subprocess',
        playback_only = false,
        capture_stdout = true,
        args = {'wmic', 'logicaldisk', 'get', 'caption'}
    })
    if result.status ~= 0 then return msg.error('could not read windows root') end

    local root = {}
    for drive in result.stdout:gmatch("%a:") do
        table.insert(root, drive..'/')
    end
    return root
end

local function in_root(drive, root)
    for _, item in ipairs(root) do
        if item.name == drive then return true end
    end
    return false
end

local function import_drives()
    local drives = get_drives()
    local root = fb.get_root()

    for _, drive in ipairs(drives) do
        if not in_root(drive, root) then
            fb.insert_root_item({ name = drive })
        end
    end
end

local keybind = {
    key = 'Ctrl+r',
    name = 'import_root_drives',
    command = import_drives,
    parser = 'root',
    passthrough = true
}

return {
    setup = import_drives,
    keybinds = { keybind }
}

```

**Comment by PhoenixCODE2322** [comment]
Thank you, will you be adding this officially to as addons ?

**Comment by CogentRedTester** [comment]
No guarantees, but this seems useful enough that there is a good chance I will tidy it up and add it, yes.

**Comment by CogentRedTester** [comment]
> > ```lua
> > return {
> >     version = '1.3.0'
> >     setup = import_drives,
> >     keybinds = { keybind }
> > }
> > ```
> 
> There is a small mistake. It should be:
> 
> > ```lua
> > return {
> >     version = '1.3.0',
> >     setup = import_drives,
> >     keybinds = { keybind }
> > }
> > ```

Fixed, thanks.
