### ISSUE TITLE
Single character directories not opening from root

### ISSUE THREAD

**Issue by CogentRedTester** [CogentRedTester/mpv-file-browser#76]
### Discussed in https://github.com/CogentRedTester/mpv-file-browser/discussions/75

<div type='discussions-op-text'>

<sup>Originally posted by **LinArcX** October 17, 2022</sup>
I mounted two NTFS partitions on `/mnt/D` and `/mnt/E` on my Linux machine.
These are the equivalent of `D:\` and `E:\` on my window os.

The problem is that when I want to define `root` in `file_browser.conf` and I open mpv-file-browser in MPV, I see two green labels and I can't search or enter through them.(Seems they are locked for exploration but don't know why). This is how I defined `root`:
```
root=~/,/mnt/D/video/,/mnt/E/video/,
```
</div>

**Comment by CogentRedTester** [comment]
@LinArcX can you check if the latest version of the script has fixed this?

**Comment by LinArcX** [comment]
Hm... It works somehow. when I press `Ctrl+o`, it opens all the files in the current directory, instead of showing the content of the root element in `file-browser.conf`.

**Comment by CogentRedTester** [comment]
That file you've posted is a `file-browser-keybinds.json` file not a `file_browser.conf` file. Also you don't need to keep my example bindings in there, you can and should remove them.

Also opening the browser for the first time will open whichever directory your current file is in. That's just how it's setup to work. You can press the `HOME` button to jump to the root.

**Comment by LinArcX** [comment]
Ok sorry for my mistake. I tested it and now it's working very well. Thanks for the update.

Just a little issue still persists, If I run MPV like this:
`mpv --player-operation-mode=pseudo-gui`

I can explore directories easily with `mpv-file-browser`, but unfortunately, I can't play any video. Why?

Edit: There's no log file or error generated during this process.
