### ISSUE TITLE
Getting an error

### ISSUE THREAD

**Issue by BhaturaGuy** [CogentRedTester/mpv-file-browser#85]
[file_browser] Lua error: ...sers\Devraj\AppData\Roaming/mpv/scripts/file-browser.lua:2147: invalid json syntax for C:\Users\Devraj\AppData\Roaming/mpv/script-opts/file-browser-keybinds.json

**Comment by po5** [comment]
Read the error.

**Comment by BhaturaGuy** [comment]
Turns out I can not use `|` to separate keybinds like it was possible to separate whitelist in `manager.json`
