### ISSUE TITLE
default background for audio files

### ISSUE THREAD

**Issue by muzzol** [CogentRedTester/mpv-file-browser#86]
this is a feature request to add a default background for audio files.

I've tried with some kind of combination of --external-file and --lavfi-complex settings but they apply for all files, no only for audio.

It would be nice to have a background image of video to be displayed when playing audio.

thanks a lot for this nice script!

**Comment by CogentRedTester** [comment]
This really has nothing to do with file-browser. Try using [mpv-coverart](https://github.com/CogentRedTester/mpv-coverart) instead. It has a placeholder option for default background images.
