### ISSUE TITLE
Show only video files

### ISSUE THREAD

**Issue by ichirou2910** [CogentRedTester/mpv-file-browser#9]
Just found this script and while so far I'm happy with it, there is this thing that is a bit uncomfortable
Is it possible to hide irrelevant files (non-video, hidden files/folders) in the browser? Cuz usually there are subtitles files in folder and I don't really like seeing it. If that's possible then I have nothing to ask more.

**Comment by CogentRedTester** [comment]
Hmm, files would definitely be possible, but how would you classify hiddem folders?

**Comment by CogentRedTester** [comment]
How does that look? I'll hold off on folders for now unless you have a good idea for how they would be filtered.

**Comment by ichirou2910** [comment]
Oh I didn't realize this script target windows too. For linux it's will just be folders/files that have the dot prefix like .config or .local. For windows I really don't have any idea too.

**Comment by CogentRedTester** [comment]
Yes, the point of the script is to use the mpv APIs to create a browser that works identically on all platforms. I could add a directory filter for linux that removes dot directories, but it would have to be off by default since those are valid directories in windows. Would that be acceptable?

**Comment by ichirou2910** [comment]
sure, that's totally fine by me :+1:

**Comment by CogentRedTester** [comment]
There we go. Confirm it works and then we can close the issue.

**Comment by ichirou2910** [comment]
Confirmed it works. Thank you very much. :tada:
