### ISSUE TITLE
How to browse WebDAV server/Dir

### ISSUE THREAD

**Issue by ddunniu** [CogentRedTester/mpv-file-browser#93]
How to browser WebDAV server/Dir，And The WebDAV need a password.

**Comment by aprils148** [comment]
Currently there is no webdav browsing addon, but I hope to have one in the future.

**Comment by CogentRedTester** [comment]
Yes, currently this is not supported. An addon could be made, but I'm very busy and don't have easy access to a WebDav server for testing. Of course there is nothing stopping people other from writing an addon themselves.
