### ISSUE TITLE
always pointing to the current video directory

### ISSUE THREAD

**Issue by liJie-wk** [CogentRedTester/mpv-file-browser#94]
I want to open the file browser in non-idle mode always pointing to the current video directory, not the previous history directory, what do I need to do?

**Comment by liJie-wk** [comment]
My "if state.directory == nil then..." judgment in open() solved the problem by adding "or state.directory ~= current_file.directory", and I don't know if it will cause other problems

**Comment by CogentRedTester** [comment]
Here's a little addon I wrote that will do what you want without needing to modify the actual script. This will allow the behaviour to keep working when updating the script. 

```lua
local mp = require 'mp'
local fb = require 'file-browser'

mp.add_key_binding(nil, 'browse-files/open-current-dir', function ()
    local dir = fb.get_current_file().directory

    if  not fb.get_open_status()
        and fb.get_directory() ~= dir
    then
        mp.commandv('script-message-to', 'file_browser', 'browse-directory', dir)
        return;
    end

    mp.commandv('script-binding', 'file_browser/browse-files')
end)

return {}

```

**Comment by liJie-wk** [comment]
Ok, thank you very much
